version: "3"
services:
    judger-api:
        container_name: judger-api
        build:
            context: .
            dockerfile: src/Ilmhub.Judge.Api/Dockerfile
        read_only: true
        ports:
            - "0.0.0.0:5000:8080"