version: "3"

services:
    judger-api:
        restart: always
        container_name: judger
        image: davidwahid/judger
        build:
            context: .
            dockerfile: ./src/Ilmhub.Judge.Api/Dockerfile
        ports:
            - "4000:5000"
        environment:
            - JAEGER_ENDPOINT=http://jaeger:4317
            - MESSAGING__RABBITMQ__HOST=rabbitmq
        depends_on:
            - jaeger
            - rabbitmq
    
    jaeger:
        restart: always
        container_name: jaeger
        image: jaegertracing/all-in-one:latest
        environment:
            COLLECTOR_ZIPKIN_HOST_PORT: 9411
            COLLECTOR_OTLP_ENABLED: true
        ports:
        - 16686:16686
        - 9411:9411
        - 6831:6831
        - 5778:5778
        - 4317:4317
        - 4318:4318
    
    rabbitmq:
        container_name: rabbitmq
        image: heidiks/rabbitmq-delayed-message-exchange:latest
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        healthcheck:
            test: [ "CMD", "nc", "-z", "localhost", "5672" ]
            interval: 5s
            timeout: 15s
            retries: 1